### ISSUE TITLE
Optionally clear output directory (or not)

### ISSUE THREAD

**Issue by nuvitong** [openapi-processor/openapi-processor-base#123]
With #42 you added the feature, to clear the output directory automatically. But what, if you process two APIs into the same output directory? In this case only the code of the latest execution will stay.

So, it would be great, if the automatic directory clearing could be disabled by option (e.g. system variable of mvn call).

What do you think?

**Comment by hauner** [comment]
I could add an option to disable the auto delete but I would like to understand your use case.

Generating multiple apis into the same directory will overwrite interfaces and dtos if they contain identical names. To avoid this I recommend to use one target dir (and java package) for each api.

What is the reasoning behind using the same target directory?

**Comment by nuvitong** [comment]
Our target directory is `generated/src/main/java` as we check in the generated api code into the code repository. The separation of the generated classes is only by package.

Does that clarify our use case?

**Comment by hauner** [comment]
ok, I will add an option to disable it.

**Comment by nuvitong** [comment]
That is great news for us. Thank you very much.

**Comment by hauner** [comment]
released with openapi-processor-spring/micronaut 2024.2
